name: Jira Create release
description: Create a new Jira release
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  project:
    description: Key of the project
    required: true
  name:
    description: "Release name"
    required: true
outputs:
  issue:
    description: Id of the newly created release
runs:
  using: 'node16'
  main: './dist/index.js'
